services:
  ppl_api:
    container_name: ppl_api
    volumes:
      - ./prisma:/app/prisma
    ports:
      - '8001:8001'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx
    restart: unless-stopped
    command: npm run start:prod

volumes:
  prisma:

networks:
  nginx:
    external: true
    name: nginx
