name: Deploy to Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files via SCP
        env:
          SSHPASS: ${{ secrets.ROOT_SSH_PASSWORD }}
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -r ./* root@194.169.160.97:/root/eldraxis

      - name: Execute remote commands
        env:
          SSHPASS: ${{ secrets.ROOT_SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no root@194.169.160.97 << 'EOF'
            cd /root/eldraxis
            systemctl stop eldraxis
            npx prisma db push
            npm run build
            systemctl start eldraxis
          EOF
